---
#https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-debian-8
- name: Install Dependencies
  apt: name={{ item }} state=latest
  with_items:
    - openvpn
    - easy-rsa
- name: Copy config
  copy: src=server.conf dest=/etc/openvpn/
- name: Copy config
  copy: src=sysctl.conf dest=/etc/
- name: Copy config
  copy: src=before.rules dest=/etc/ufw/
- name: UFW config
  copy: src=ufw dest=/etc/default/
- name: UFW enable ssh
  ufw: rule=allow name=ssh state=enabled
- name: UFW 1194/udp
  ufw: rule=allow port=1194 proto=udp state=enabled
- name: DH cert
  command: openssl dhparam -out /etc/openvpn/dh4096.pem 4096 creates=/etc/openvpn/dh4096.pem
- name: Copy easy-rsa
  command: "cp -r /usr/share/easy-rsa {{easy_rsa_directory}} creates={{easy_rsa_directory}}"
- name: Copy new files
  copy: "src=easy-rsa/ dest={{easy_rsa_directory}}/ mode=u+rx"
- name: Clean all
  shell: "{{easy_rsa_directory}}/clean-all chdir={{easy_rsa_directory}}"
  environment: "{{easy_rsa}}"
- name: Build CA
  shell: "{{easy_rsa_directory}}/build-ca chdir={{easy_rsa_directory}}"
  environment: "{{easy_rsa}}"
- name: Build server key
  shell: "{{easy_rsa_directory}}/build-key-server server chdir={{easy_rsa_directory}}"
  environment: "{{easy_rsa}}"
- name: Build client key
  shell: "{{easy_rsa_directory}}/build-key client chdir={{easy_rsa_directory}}"
  environment: "{{easy_rsa}}"
- name: Build client.ovpn
  shell: "{{easy_rsa_directory}}/build-client-ovpn chdir={{easy_rsa_directory}}"
  environment: "{{easy_rsa}}"
- name: Copy generated certs
  copy: "src={{easy_rsa_directory}}/keys/{{ item }} dest=/etc/openvpn remote_src=true"
  with_items:
    - server.crt
    - server.key
    - ca.crt
- name: Fetch client.ovpn from remote
  fetch: "src={{easy_rsa_directory}}/client.ovpn dest=tmp/ fail_on_missing=yes flat=yes"
- name: Remove temporary directory
  file: "path={{easy_rsa_directory}} state=absent"
- name: Start VPN server
  service: name=openvpn state=restarted
