---
- name: Upgrade packages
  apt: upgrade=full update_cache=yes cache_valid_time=3600
- name: Install Dependencies
  apt: name={{item}} state=latest
  with_items:
    - vim
    - exfat-fuse
    - wavemon
    - openssl
    - ufw
    - htop
- name: Limit SSH connections
  ufw: rule=limit name=ssh state=enabled
- name: Disable all ports
  ufw: state=enabled policy=deny logging=on
- name: Expand rootfs
  command: /usr/bin/raspi-config --expand-rootfs
  notify: Reboot
- name: Set new password for pi user
  user: "name=pi state=present password={{ password | password_hash('sha512') }}"
  when: password is defined
