---
- name: Upgrade packages
  apt: upgrade=full update_cache=yes cache_valid_time=3600
- name: Install Dependencies
  apt: name={{item}} state=latest
  with_items:
    - vim
    - exfat-fuse
    - wavemon
    - openssl
    - ufw
# - user: "name=pi state=present password={{ password }}"
- hostname: "name={{hostname}}"
- name: Copy sshd config
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify: Restart SSH
- name: Copy public key
  authorized_key: user=pi key="{{ item }}" state=present exclusive=yes
  with_file:
    - "{{ public_key }}"
